/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package multiplicacion.por.strassen;

import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asus
 */
public class Ventana extends javax.swing.JFrame {
    
    

    public JTextField txt1[][];
    public JTextField txt2[][];
    public int a[][];
    public int b[][];
    public int filas1, columnas1, filas2, columnas2;

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        this.setTitle("Multiplicación de matrices por el método de Strassen");
        this.setLocation(50,50);
        initComponents();
        btnMultiplicar.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFilas1 = new javax.swing.JTextField();
        txtColumnas1 = new javax.swing.JTextField();
        txtFilas2 = new javax.swing.JTextField();
        txtColumnas2 = new javax.swing.JTextField();
        btnIniciar = new javax.swing.JButton();
        btnMultiplicar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Número de filas:");

        jLabel2.setText("Número de filas:");

        jLabel3.setText("Número de columnas:");

        jLabel4.setText("Número de columnas:");

        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        btnMultiplicar.setText("Multiplicar");
        btnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtFilas1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtFilas2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtColumnas1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtColumnas2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMultiplicar)
                    .addComponent(btnIniciar))
                .addContainerGap(740, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFilas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtColumnas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIniciar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtColumnas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtFilas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMultiplicar))
                .addContainerGap(433, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed

        if (txtColumnas1.getText().equals(txtFilas2.getText())) {
            filas1 = Integer.parseInt(txtFilas1.getText());
            columnas1 = Integer.parseInt(txtColumnas1.getText());
            filas2 = Integer.parseInt(txtFilas2.getText());
            columnas2 = Integer.parseInt(txtColumnas2.getText());
            
            btnMultiplicar.setEnabled(true);
            
            int resultado[][] = new int[filas1][columnas2];

            txt1 = new JTextField[filas1][columnas1];

            for (int i = 0; i < filas1; i++) {
                for (int j = 0; j < columnas1; j++) {
                    JTextField t = new JTextField();
                    txt1[i][j] = t;
                    this.add(t);
                    t.setBounds(25 + (40 * j), 100 + (50 * i), 30, 30);
                }

            }

            txt2 = new JTextField[filas2][columnas2];

            for (int i = 0; i < filas2; i++) {
                for (int j = 0; j < columnas2; j++) {
                    JTextField t = new JTextField();
                    txt2[i][j] = t;
                    this.add(t);
                    t.setBounds(400 + (40 * j), 100 + (50 * i), 30, 30);
                }

            }

        } else {
            JOptionPane.showMessageDialog(null,"No se puede realizar esta multipliación" );
        }
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicarActionPerformed

        int aux[] = {filas1, filas2, columnas1, columnas2};

        int temp = 0;
        for (int i = 0; i < 3; i++) {
            for (int j = i + 1; j < 4; j++) {
                if (aux[i] > aux[j]) {
                    temp = aux[i];
                    aux[i] = aux[j];
                    aux[j] = temp;
                }
            }
        }

        int mayor = aux[3];
        System.out.println(mayor);

        if (mayor == 3) {
            mayor = 4;
        } else if (mayor > 4 && mayor < 8) {
            mayor = 8;
        }

        a = new int[mayor][mayor];
        b = new int[mayor][mayor];

        for (int i = 0; i < mayor; i++) {
            for (int j = 0; j < mayor; j++) {
                a[i][j] = 0;
                b[i][j] = 0;
            }
        }

        for (int i = 0; i < filas1; i++) {
            for (int j = 0; j < columnas1; j++) {
                a[i][j] = Integer.parseInt(txt1[i][j].getText());
                System.out.print(" " + a[i][j]);
            }
            System.out.println("");
        }
        System.out.println("********************************");
        for (int i = 0; i < filas2; i++) {
            for (int j = 0; j < columnas2; j++) {
                b[i][j] = Integer.parseInt(txt2[i][j].getText());
                System.out.print(" " + b[i][j]);
            }
            System.out.println("");
        }

        MultiplicacionPorStrassen miMultiplicacion = new MultiplicacionPorStrassen(a, b);

        int c[][] = miMultiplicacion.resultado;

        for (int i = 0; i < filas1; i++) {
            for (int j = 0; j < columnas2; j++) {
                JTextField t = new JTextField();
                this.add(t);
                t.setBounds(775 + (40 * j), 100 + (50 * i), 30, 30);
                t.setText("" + c[i][j]);
            }
        }

    }//GEN-LAST:event_btnMultiplicarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnMultiplicar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JTextField txtColumnas1;
    public javax.swing.JTextField txtColumnas2;
    public javax.swing.JTextField txtFilas1;
    public javax.swing.JTextField txtFilas2;
    // End of variables declaration//GEN-END:variables
}
